In [26]:
import pandas as pd

population_df = pd.read_csv("population_df.csv")
hapy_country_df=pd.read_csv("hapy_country_df.csv")

In [27]:
display(hapy_country_df.head)
display(population_df.head)

<bound method NDFrame.head of      happiness_rank  year                       country              region  \
0                 1  2015                   Switzerland      Western Europe
1                 2  2015                       Iceland      Western Europe
2                 3  2015                       Denmark      Western Europe
3                 4  2015                        Norway      Western Europe
4                 5  2015                        Canada       North America
..              ...   ...                           ...                 ...
777             152  2019                        Rwanda  Sub-Saharan Africa
778             153  2019  Tanzania, United Republic of  Sub-Saharan Africa
779             154  2019                   Afghanistan       Southern Asia
780             155  2019      Central African Republic  Sub-Saharan Africa
781             156  2019                   South Sudan  Sub-Saharan Africa

     happiness_score  gdp_percapita  life_expectancy   family  freedom  \
0              7.587        1.39651          0.94143  1.34951  0.66557
1              7.561        1.30232          0.94784  1.40223  0.62877
2              7.527        1.32548          0.87464  1.36058  0.64938
3              7.522        1.45900          0.88521  1.33095  0.66973
4              7.427        1.32629          0.90563  1.32261  0.63297
..               ...            ...              ...      ...      ...
777            3.334        0.35900          0.61400  0.71100  0.55500
778            3.231        0.47600          0.49900  0.88500  0.41700
779            3.203        0.35000          0.36100  0.51700  0.00000
780            3.083        0.02600          0.10500  0.00000  0.22500
781            2.853        0.30600          0.29500  0.57500  0.01000

     generosity  government_corruption
0       0.29678                0.41978
1       0.43630                0.14145
2       0.34139                0.48357
3       0.34699                0.36503
4       0.45811                0.32957
..          ...                    ...
777     0.21700                0.41100
778     0.27600                0.14700
779     0.15800                0.02500
780     0.23500                0.03500
781     0.20200                0.09100

[782 rows x 11 columns]>

<bound method NDFrame.head of           country  year   total_pop  pop_density    age_pop country_clean
0     Afghanistan  2015  33831763.5    52.105301  15.489743   Afghanistan
1     Afghanistan  2016  34700612.0    53.443440  15.680543   Afghanistan
2     Afghanistan  2017  35688934.5    54.965585  15.868287   Afghanistan
3     Afghanistan  2018  36743039.0    56.589043  16.050842   Afghanistan
4     Afghanistan  2019  37856121.0    58.303333  16.234260   Afghanistan
...           ...   ...         ...          ...        ...           ...
1175       Zambia  2015  16399088.5    22.059872  16.114668        Zambia
1176       Zambia  2016  16914423.0    22.753095  16.262689        Zambia
1177       Zambia  2017  17441319.5    23.461870  16.426126        Zambia
1178       Zambia  2018  17973569.0    24.177846  16.593368        Zambia
1179       Zambia  2019  18513839.5    24.904612  16.762938        Zambia

[1180 rows x 6 columns]>

In [28]:
happy_population_df = hapy_country_df.merge(population_df[["country_clean", "year", "total_pop", "pop_density", "age_pop"]]
    ,left_on=["country", "year"],
    right_on=["country_clean", "year"],
    how="left")

In [29]:
happy_population_df = happy_population_df.drop(columns=["country_clean"])

In [30]:
display(happy_population_df.head())
display(happy_population_df.shape)
display(happy_population_df.isna().sum())

,happiness_rank,year,country,region,happiness_score,gdp_percapita,life_expectancy,family,freedom,generosity,government_corruption,total_pop,pop_density,age_pop
0,1,2015,Switzerland,Western Europe,7.587,1.39651,0.94143,1.34951,0.66557,0.29678,0.41978,8283934.0,207.139778,41.259268
1,2,2015,Iceland,Western Europe,7.561,1.30232,0.94784,1.40223,0.62877,0.43630,0.14145,330951.5,3.301492,34.940392
2,3,2015,Denmark,Western Europe,7.527,1.32548,0.87464,1.36058,0.64938,0.34139,0.48357,5683701.0,134.068524,40.497999
3,4,2015,Norway,Western Europe,7.522,1.45900,0.88521,1.33095,0.66973,0.34699,0.36503,5189771.0,17.058933,38.176429
4,5,2015,Canada,North America,7.427,1.32629,0.90563,1.32261,0.63297,0.45811,0.32957,35962234.0,3.954716,39.629038

(782, 14)

happiness_rank            0
year                      0
country                   0
region                    0
happiness_score           0
gdp_percapita             0
life_expectancy           0
family                    0
freedom                   0
generosity                0
government_corruption     1
total_pop                12
pop_density              12
age_pop                  12
dtype: int64

In [31]:
happy_population_df[happy_population_df["total_pop"].isna()]

,happiness_rank,year,country,region,happiness_score,gdp_percapita,life_expectancy,family,freedom,generosity,government_corruption,total_pop,pop_density,age_pop
65,66,2015,North Cyprus,Western Europe,5.695,1.208060,0.923560,1.070080,0.490270,0.261690,0.142800,NaN,NaN,NaN
92,93,2015,Macedonia,Central and Eastern Europe,5.007,0.918510,0.735450,1.002320,0.334570,0.223590,0.053270,NaN,NaN,NaN
219,62,2016,North Cyprus,Western Europe,5.771,1.311410,0.841420,0.818260,0.435960,0.263220,0.165780,NaN,NaN,NaN
233,76,2016,Somalia,Sub-Saharan Africa,5.440,0.000000,0.114660,0.336130,0.567780,0.272250,0.311800,NaN,NaN,NaN
252,95,2016,Macedonia,Central and Eastern Europe,5.121,1.019300,0.647380,0.782360,0.276680,0.235070,0.070470,NaN,NaN,NaN
254,97,2016,Somaliland Region,Sub-Saharan Africa,5.057,0.255580,0.331080,0.758620,0.391300,0.514790,0.367940,NaN,NaN,NaN
375,61,2017,North Cyprus,Western Europe,5.810,1.346911,0.834647,1.186303,0.471204,0.266846,0.155353,NaN,NaN,NaN
406,92,2017,Macedonia,Central and Eastern Europe,5.175,1.064578,0.644948,1.207893,0.325906,0.253761,0.060278,NaN,NaN,NaN
407,93,2017,Somalia,Sub-Saharan Africa,5.151,0.022643,0.113989,0.721151,0.602127,0.291631,0.282410,NaN,NaN,NaN
558,89,2018,Macedonia,Central and Eastern Europe,5.185,0.959000,0.691000,1.239000,0.394000,0.173000,0.052000,NaN,NaN,NaN
567,98,2018,Somalia,Sub-Saharan Africa,4.982,0.000000,0.115000,0.712000,0.674000,0.238000,0.282000,NaN,NaN,NaN
737,112,2019,Somalia,Sub-Saharan Africa,4.668,0.000000,0.268000,0.698000,0.559000,0.243000,0.270000,NaN,NaN,NaN

In [32]:
happy_population_df.loc[happy_population_df["total_pop"].isna(),"country"].unique()

<StringArray>
['North Cyprus', 'Macedonia', 'Somalia', 'Somaliland Region']
Length: 4, dtype: str